namespace AudioQualityAnalyzer.Tests.TestSupport;

/// <summary>Locates the Phase 13 reference/ dataset (regenerated by scripts/generate-reference-dataset.sh) from a test's runtime output directory.</summary>
internal static class ReferenceDataset
{
    public static string FindPath(string relativePath)
    {
        var dir = AppContext.BaseDirectory;
        while (dir is not null && !Directory.Exists(Path.Combine(dir, "reference")))
        {
            dir = Directory.GetParent(dir)?.FullName;
        }

        if (dir is null)
        {
            throw new DirectoryNotFoundException(
                "Could not locate the reference/ dataset directory by walking up from the test output directory. " +
                "Run scripts/generate-reference-dataset.sh from the repo root first.");
        }

        return Path.Combine(dir, "reference", relativePath);
    }
}
