<Project Sdk="Microsoft.NET.Sdk.BlazorWebAssembly">

  <PropertyGroup>
    <OverrideHtmlAssetPlaceholders>true</OverrideHtmlAssetPlaceholders>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.Components.WebAssembly" Version="10.0.11" />
    <PackageReference Include="Microsoft.AspNetCore.Components.WebAssembly.DevServer" Version="10.0.11" PrivateAssets="all" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Spectra.Core\Spectra.Core.csproj" />
    <ProjectReference Include="..\Spectra.Audio\Spectra.Audio.csproj" />
    <ProjectReference Include="..\Spectra.Analysis\Spectra.Analysis.csproj" />
  </ItemGroup>

</Project>
